### PR TITLE
Update to Tensorflow v1 and Keras v2

### PR DESCRIPTION
**Pull request by andrewpaster**

### CODE REVIEW

**Comment by domluna** [comment]
I'll test this out.

**Comment by kvalev** [comment]
Any plans to merge this commit?

**Comment by mvirgo** [comment]
Still pending updating classroom to these versions as well.

**Comment by mvirgo** [comment]
Vienna has updated to the new workspace versions (which include Tensorflow V1 and Keras V2) herein, so closing this out.

**Pull request closed without merging**
