### PR TITLE
adding libraries that solve some errors in my linux environment

### PR DESCRIPTION
**Pull request by agonzale34**
when I was working in the first project I detected some errors and I solved by adding 2 libraries

### CODE REVIEW

**Comment by mvirgo** [comment]
OpenCV is already being installed with `opencv3` (the Anaconda name for it). Did you receive an error message when it got to opencv3?

`requests` is mentioned [here](https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/doc/configure_via_anaconda.md) as something that is sometimes missing depending on installation, although not always for whatever reason.

Note that we also have both the CPU and GPU environments, so those files need to be consistent.

**Comment by agonzale34** [comment]
> OpenCV is already being installed with `opencv3` (the Anaconda name for it). Did you receive an error message when it got to opencv3?
> 
> `requests` is mentioned [here](https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/doc/configure_via_anaconda.md) as something that is sometimes missing depending on installation, although not always for whatever reason.
> 
> Note that we also have both the CPU and GPU environments, so those files need to be consistent.

I tested in two different machines and I got a error in python with the import of opencv3, and when I added the library with pip solve the problem, but then starting having errors with the requests import. So adding the library with pip solve too, tomorrow I will try configure the GPU environments and check if works by default or I have to add the libraries too.

**Comment by mvirgo** [comment]
What OS (and version of them) are you using when receiving the error? Wondering if that is part of it. If it's only happening on one OS, but doesn't break anything for different OS's by installing through pip instead of conda, probably makes sense to remove it from earlier in addition to your change.

**Comment by agonzale34** [comment]
I tested in Manjaro Linux, I can test it in Windows 10 if is necessary to be sure that my change in the environment file doesn't break anything.

**Comment by mvirgo** [comment]
I can get it tested on each OS, just wanted to confirm yours :) Yeah, my guess is that Arch Linux may not have `opencv3` under conda, while Ubuntu looks like it does. I'm going to request to edit the file to remove the `opencv3` at the top, then I'll do some testing before merging.

**Comment by agonzale34** [comment]
@mvirgo I make the changes you requested.

**Comment by mvirgo** [comment]
Thank you! Tests worked out across platforms.

**Pull request merged**
